avoid-breaking-exported-api = false
arithmetic-side-effects-allowed = [
    # daur internal type names
    "audio::Audio",
    "audio::sample::duration::Duration",
    "audio::sample::pair::Pair",
    "audio::sample::Sample",
    "metre::duration::Duration",
    "metre::duration::non_zero::NonZeroDuration",
    "metre::instant::Instant",
    "metre::relative::instant::Instant",
    "metre::time_signature::TimeSignature",
    "metre::changing::Changing",
    "note::pitch::Pitch",
    "ratio::non_zero::NonZeroRatio",
    "ratio::Ratio",
    "time::duration::Duration",
    "time::instant::Instant",
    "time::period::Period",
    "ui::direction::Direction",
    "ui::length::Length",
    "ui::offset::Offset",
    "ui::point::Point",
    "ui::vector::Vector",

    # type names for other crates
    "daur::audio::Sample",
    "daur::ui::Direction",
    "daur::ui::Length",
    "daur::ui::Point",
    "daur::ui::Offset",
    "daur::ui::Vector",
]
# `f` is used in Display::fmt 
allowed-idents-below-min-chars = ["f", "x", "y", "X", "Y"]
