arithmetic-side-effects-allowed = [
    "length::Length",
    "length::offset::Offset",
    "time::duration::Duration",
    "time::instant::Instant",
    "time::Ratio",
]
# `f` is used in Display::fmt 
allowed-idents-below-min-chars = ["f", "x", "y"]
