arithmetic-side-effects-allowed = [
    "pitch::Pitch",
    "measure::length::Length",
    "measure::offset::Offset",
    "ratio::Ratio",
    "ratio::non_zero::NonZeroRatio",
    "time::duration::Duration",
    "time::duration::non_zero::NonZeroDuration",
    "time::instant::Instant",
]
# `f` is used in Display::fmt 
allowed-idents-below-min-chars = ["f", "x", "y"]
