[target.'cfg(all())']
rustflags = [
    "--allow", "unstable_name_collisions",

    "--deny", "absolute_paths_not_starting_with_crate",
    "--deny", "ambiguous_negative_literals",
    "--deny", "deprecated_safe_2024",
    "--deny", "explicit_outlives_requirements",
    "--deny", "let_underscore_drop",
    "--deny", "meta_variable_misuse",
    "--deny", "missing_copy_implementations",
    "--deny", "missing_debug_implementations",
    "--deny", "missing_docs",
    "--deny", "non_ascii_idents",
    "--deny", "redundant_imports",
    "--deny", "redundant_lifetimes",
    "--deny", "trivial_casts",
    "--deny", "trivial_numeric_casts",
    "--deny", "unit_bindings",
    "--deny", "unsafe_attr_outside_unsafe",
    "--deny", "unused_crate_dependencies",
    "--deny", "unused_extern_crates",
    "--deny", "unused_import_braces",
    "--deny", "unused_lifetimes",
    "--deny", "unused_macro_rules",
    "--deny", "unused_qualifications",
    "--deny", "clippy::all",
    "--deny", "clippy::pedantic",
    "--deny", "clippy::absolute_paths",
    "--deny", "clippy::alloc_instead_of_core",
    "--deny", "clippy::allow_attributes",
    "--deny", "clippy::allow_attributes_without_reason",
    # not `clippy::arbitrary_source_item_ordering` since it wasn't customisable enough
    "--deny", "clippy::arithmetic_side_effects",
    # not `clippy::as_conversions` since it is covered by more specific lints
    "--deny", "clippy::as_underscore",
    "--deny", "clippy::assertions_on_result_states",
    # not `clippy::big_endian_bytes` since usage is explicit
    "--deny", "clippy::cfg_not_test",
    "--deny", "clippy::clone_on_ref_ptr",
    "--deny", "clippy::create_dir",
    "--deny", "clippy::dbg_macro",
    "--deny", "clippy::decimal_literal_representation",
    "--deny", "clippy::deref_by_slicing",
    # not `clippy::disallowed_script_idents` since it is covered by `non_ascii_idents`
    "--deny", "clippy::else_if_without_else",
    "--deny", "clippy::empty_drop",
    "--deny", "clippy::empty_enum_variants_with_brackets",
    "--deny", "clippy::empty_structs_with_brackets",
    # not `clippy::error_impl_error` since we don't have many `Error` types
    # not `clippy::exhaustive_enums` since exhaustivity is good
    # not `clippy::exhaustive_structs` since exhaustivity is good
    "--deny", "clippy::exit",
    "--deny", "clippy::expect_used",
    "--deny", "clippy::field_scoped_visibility_modifiers",
    "--deny", "clippy::filetype_is_file",
    # not `clippy::float_arithmetic` since we're not embedded
    "--deny", "clippy::float_cmp_const",
    "--deny", "clippy::fn_to_numeric_cast_any",
    # not `clippy::get_unwrap` since it is more explicit
    # not `clippy::host_endian_bytes` since usage is explicit
    "--deny", "clippy::impl_trait_in_params",
    # not `clippy::implicit_return` since explicit returns are ugly
    "--deny", "clippy::indexing_slicing",
    # not `clippy::infinite_loop` until `!` gets stabilised
    # not `clippy::inline_asm_x86_att_syntax` since we don't use asm
    # not `clippy::inline_asm_x86_intel_syntax` since we don't use asm
    "--deny", "clippy::integer_division",
    # not `clippy::integer_division_remainder_used` since we don't do cryptography
    # not `clippy::iter_over_hash_type` since if you care about order you don't use a hash type
    # not `clippy::large_include_file` since usage is explicit
    "--deny", "clippy::let_underscore_must_use",
    # not `clippy::little_endian_bytes` since usage is explicit
    "--deny", "clippy::lossy_float_literal",
    #not `clippy::map_err_ignore`
    "--deny", "clippy::map_with_unused_argument_over_ranges",
    "--deny", "clippy::min_ident_chars",
    "--deny", "clippy::missing_assert_message",
    "--deny", "clippy::missing_asserts_for_indexing",
    # not `clippy::missing_docs_in_private_items` for now
    # not `clippy::missing_inline_in_public_items`, is it still relevant?
    # not `clippy::missing_trait_methods` at least on the crate level
    "--deny", "clippy::mixed_read_write_in_expression",
    # not `clippy::mod_module_files` since we deny `clippy::self_module_files`
    "--deny", "clippy::module_name_repetitions",
    "--deny", "clippy::modulo_arithmetic",
    # not `clippy::multiple_inherent_impl` until splitting across files is supported
    "--deny", "clippy::multiple_unsafe_ops_per_block",
    "--deny", "clippy::mutex_atomic",
    "--deny", "clippy::mutex_integer",
    "--deny", "clippy::needless_raw_strings",
    "--deny", "clippy::non_ascii_literal", # since some chars look similar but aren't
    "--deny", "clippy::non_zero_suggestions",
    "--deny", "clippy::panic",
    "--deny", "clippy::panic_in_result_fn",
    # not `clippy::partial_pub_fields` since it saves you from writing getters and setters
    "--deny", "clippy::pathbuf_init_then_push",
    # not `clippy::pattern_type_mismatch` for now
    "--deny", "clippy::print_stderr",
    "--deny", "clippy::print_stdout",
    # not `clippy::pub_use` since it allows you to break up code into files without complicating the module structure
    # not `clippy::pub_with_shorthand` since we deny `clippy::pub_without_shorthand`
    "--deny", "clippy::pub_without_shorthand",
    # not `clippy::question_mark_used` at least on the crate level
    "--deny", "clippy::rc_buffer",
    "--deny", "clippy::rc_mutex",
    "--deny", "clippy::redundant_type_annotations",
    # not `clippy::ref_patterns` since I find it ugly
    "--deny", "clippy::renamed_function_params",
    "--deny", "clippy::rest_pat_in_fully_bound_structs",
    "--deny", "clippy::same_name_method",
    "--deny", "clippy::self_named_module_files",
    "--deny", "clippy::semicolon_inside_block", # this means that semicolons go inside blocks
    # not `clippy::semicolon_outside_block` since we deny `clippy::semicolon_inside_block`
    # not `clippy::separated_literal_suffix` since we deny `unseparated_literal_suffix`
    # not `clippy::shadow_reuse`
    # not `clippy::shadow_same`
    # not `clippy::shadow_unrelated`
    # not `clippy::single_call_fn` since it is useful for readability
    "--deny", "clippy::single_char_lifetime_names",
    # not `clippy::std_instead_of_alloc` since we use std
    # not `clippy::std_instead_of_core` since we use std
    "--deny", "clippy::str_to_string",
    # not `clippy::string_add` since I find it readable
    "--deny", "clippy::string_lit_chars_any",
    "--deny", "clippy::string_slice",
    "--deny", "clippy::string_to_string",
    "--deny", "clippy::suspicious_xor_used_as_pow",
    "--deny", "clippy::tests_outside_test_module",
    "--deny", "clippy::todo",
    "--deny", "clippy::try_err",
    "--deny", "clippy::undocumented_unsafe_blocks",
    "--deny", "clippy::unimplemented",
    "--deny", "clippy::unnecessary_safety_comment",
    "--deny", "clippy::unnecessary_safety_doc",
    "--deny", "clippy::unnecessary_self_imports",
    # not `clippy::unneeded_field_pattern` since exhaustivity is good
    "--deny", "clippy::unreachable",
    "--deny", "clippy::unseparated_literal_suffix",
    "--deny", "clippy::unused_result_ok",
    "--deny", "clippy::unused_trait_names",
    "--deny", "clippy::unwrap_in_result",
    "--deny", "clippy::unwrap_used",
    "--deny", "clippy::use_debug",
    "--deny", "clippy::verbose_file_reads",
    "--deny", "clippy::wildcard_enum_match_arm",
]
